### PR TITLE
Add listen function for external call.

### PR DESCRIPTION
**Pull request by asas1asas200**
I have added a listen function to call the internal listen function of `_serial`.

If I use Arduino UNO, I can only use one `SoftwareSerial` at a time.
And the `SoftwareSerial.listen()` function can help us to switch between multiple serials.
Add this feature for more flexibility.

### CODE REVIEW

**Comment by arduino12** [comment]
**Thanks for your explanation and great work!**
Please also add them to the [keywords](https://github.com/arduino12/rdm6300/blob/master/keywords.txt) file as well,
Also it will be nice to keep the original conventions and call it `is_listening` but it is your choice :)
Will merge after your next commit :)

**Comment by arduino12** [comment]
Also if you have the time to add a simple example demonstrating the use of these function for me and others to see it will be super nice 🥇 maybe create 2 `Rdm6300` instances for example?

**Comment by asas1asas200** [comment]
I have added an example for it!
And I didn't notice the class member transition of `_serial` because I read the release version, but it's fixed now.

**Comment by arduino12** [comment]
Great work @asas1asas200 !
**Thanks..!**

**Comment by arduino12** [comment]
@JessicaWoods03 
They comes with the Arduino core environment,
Just google "arduino stream.h" and find them on the **[Arduino repo](https://github.com/arduino/ArduinoCore-avr/tree/master/cores/arduino)**.

**Also,**
This is not the place to ask such questions that are not related to this pull request..

**Comment by JessicaWoods03** [comment]
Oh, sorry...this is the site I am directed to when I am working with rdm_6300...it continues to come back to this site, I am new to using Arduino's.....he has three header files listed on his header that I was not familiar with as far as were to get those-

**Pull request merged**
